-- 코드를 입력하세요
SELECT DATE_FORMAT(OS.SALES_DATE, '%Y') AS YEAR
      ,DATE_FORMAT(OS.SALES_DATE, '%m') AS MONTH
      ,UI.GENDER
      ,COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
    INNER JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID AND UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER
