-- 코드를 입력하세요
SELECT t.FOOD_TYPE, t.REST_ID, t.REST_NAME, t.FAVORITES
FROM (
  SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
         ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rn
  FROM REST_INFO
) t
WHERE t.rn = 1
ORDER BY t.FOOD_TYPE DESC;
