-- 코드를 입력하세요
WITH RECURSIVE AllHours AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 AS HOUR
  FROM AllHours
  WHERE HOUR < 23
)

SELECT 
  AllHours.HOUR,
  COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM AllHours
LEFT JOIN ANIMAL_OUTS ON AllHours.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY AllHours.HOUR
ORDER BY AllHours.HOUR;
