-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * OSA.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS OSA ON P.PRODUCT_ID = OSA.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;
