-- 코드를 입력하세요
SELECT DISTINCT CH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
JOIN CAR_RENTAL_COMPANY_CAR AS CC 
    ON CC.CAR_ID = CH.CAR_ID 
        AND CC.CAR_TYPE = '세단'
WHERE DATE_FORMAT(CH.START_DATE, '%Y-%m-%d') >= '2022-10-01' 
AND DATE_FORMAT(CH.START_DATE, '%Y-%m-%d') <= '2022-10-31'

ORDER BY CH.CAR_ID DESC


